# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2023.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: win_text_simple
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  msvc-release-x64-msbuild:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        vstoolset: [ 14.1, 14.2, 14.3 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.vstoolset }}
      - name: msvc-release-x64
        shell: cmd
        working-directory: ./
        run: |
          MSBuild -m win_text_simple.sln -p:useenv=false -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir %cd%\x64\Release\win_text_simple.exe
